%Function used to set the parameters of the methods of limits thresholding
%task.
%Author: Arthur S. Courtin
%License: MIT 

function params=set_params_method_of_limits_thresholding_task(language,baseline)

    params.baseline=baseline;
    
    params.stim_delay=1;
    params.screen_refresh_lag=0.1;
    
    params.speed=1;
    params.return=5;
    
    params.middle_color=[60 60 160];
    params.background_color =[15 15 40];
    params.text_color=[200 200 240];
    
    params.save_summary_plot=1;
    
    params.n_practice=3;
    params.n_test=3;
    
    params.cdt.direction=0;
    params.cdt.modality_idx=1;
    params.cdt.max=0;
    params.cdt.iti=5;
    
    params.wdt.direction=1;
    params.wdt.modality_idx=2;
    params.wdt.max=50;
    params.wdt.iti=5;
    
    params.hpt.direction=1;
    params.hpt.modality_idx=3;
    params.hpt.max=50;
    params.hpt.iti=10;
    
    switch language
        case 'FR'
            params.general_instructions_practice=[...
                'Nous allons commencer par une phase d´entraînement afin de vous familiariser\n avec les différentes procédures.\n\n'...
                'L´appareil placé sur votre peau peut chauffer et refroidir.\n\n'...
                'Pendant les évaluations, vous devrez utiliser le clavier pour donner vos réponses.\n'...
                'Pour chaque évaluation, nous vous indiquerons comment et quand utiliser le clavier.\n\n'...
                'Pour commencer, veuillez indiquer si l´appareil sur votre peau vous semble \n froid (←), neutre (↑) ou chaud (→).\n'...
                ];
            params.wait_instruction='Nous allons attendre un peu afin que votre peau s´habitue à la température de la thermode.';
            params.cdt_instruction_practice=[...
                'Nous allons maintenant tester votre capacité à percevoir les sensations de froid.\n\n'...
                'Veuillez appuyer sur la touche ↑ dés que vous percevez \n un refroidissement / une diminution de température.\n'...
                'Ensuite, la thermode retournera à la température de base.\n\n'...
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n La procédure débutera après quelques secondes.'...
                ];
            params.wdt_instruction_practice=[...
                'Nous allons maintenant tester votre capacité à percevoir les sensations de chaleur.\n\n'...
                'Veuillez appuyer sur la touche ↑ dés que vous percevez \n un échauffement / une augmentation de température.\n'...
                'Ensuite, la thermode retournera à la température de base.\n\n'...
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n La procédure débutera après quelques secondes.'...
                ];
            params.hpt_instruction_practice=[...
                'Nous allons maintenant tester à quelle température vous percevez de la douleur.\n\n'...
                'Votre peau sera lentement chauffée.\n'...
                'À un certain moment, vous ressentirez une seconde sensation\n en plus de la sensation de "tiède" ou de "chaud".\n'...
                'Cette seconde sensation pourra avoir une qualité de "brûlure", "piqûre", et/ou "douleur".\n'...
                'Veuillez appuyer sur la touche ↑ dès que vous percevez un tel changement.\n\n'...
                'N´attendez PAS que la sensation devienne insupportablement \n douloureuse avant d appuyer sur la touche.\n\n'...
                'Après que vous aillez poussé sur la touche, la thermode retournera à la température de base.\n\n'...
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n La procédure débutera après quelques secondes.'...
                ];
            
            params.general_instructions_test=[...
                'Nous allons maintenant commencer la phase de test.\n Toutes les procédures sont identiques à celles de la phase d´entraînement.\n\n'...
                'Pour commencer, veuillez indiquer si l´appareil sur votre peau \n vous semble froid (←), neutre (↑) ou chaud (→).\n'...
                ];
            params.cdt_instruction_test=[...
                'Veuillez appuyer sur la touche ↑ dés que\n vous percevez un refroidissement / une diminution de la température.\n'...
                'Cette procédure sera réalisée un total de 3 fois.\n\n'... 
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n'...
                'La procédure débutera après quelques secondes.\n'...
                ];
            params.wdt_instruction_test=[...
                'Veuillez appuyer sur la touche ↑ dés que \n vous percevez un échauffement / une augmentation de température.\n'...
                'Cette procédure sera réalisée un total de 3 fois.\n\n'... 
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n'...
                'La procédure débutera après quelques secondes.\n'...     
                ];
            params.hpt_instruction_test=[...
                'Veuillez appuyer sur la touche ↑ dés que \n la sensation de “chaud” ou de “très chaud” change de qualité \n'...
                'et devient une sensation de “brûlure”, “piqûre”, et/ou “douleur”.\n\n'...
                'Cette procédure sera réalisée un total de 3 fois.\n\n'... 
                'Appuyez sur la touche ↑ lorsque vous êtes prêt.e à commencer.\n'...
                'La procédure débutera après quelques secondes.\n'...
                ];
            params.cdt_question='Poussez sur ↑ dés que vous sentez un refroidissement';
            params.wdt_question='Poussez sur ↑  dés que  vous sentez un échauffement';
            params.hpt_question='Poussez sur ↑  dés que  vous sentez du brûlant, piquant, et/ou douloureux';
    
            params.end_of_task_text='Fin de la tâche';
            params.inter_trial_text='Attendez l´essai suivant';
        case 'EN'
            params.general_instructions_practice=[...
                'We will start with a practice round in which you get to familizarize \n yourself with the different procedures.\n\n'... 
                'The device placed on your skin is able to either warm or cool the skin.\n\n'...
                'In addition you will have to use the keyboard to give answers.\n'...
                'For every test, we will tell you how and when to use the keyboard.\n\n'... 
                'To start, please indicate whether the device on your skin feels \n cool (←), neutral (↑), or warm (→),.'...
                ];
            params.wait_instruction='We will wait a little bit to give you time \n to habituate to the temperature of the stimulator.';
            params.cdt_instruction_practice=[...
                'First we will test your ability to perceive cold sensations.\n\n'...
                'Please press the ↑ key immediately once you perceive \n cooling/decrease of temperature for the first time.\n'...
                'Subsequently, the thermode will warm up again, until it reaches the baseline temperature.\n\n'...
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.'...
                ];
            params.wdt_instruction_practice=[...
                'Now we will test your ability to perceive warm sensations.\n\n'...
                'Please press the ↑ key immediately once you perceive \n a warming/increase of temperature for the first time.\n'...
                'Subsequently, the thermode will cool down again, until it reaches the baseline temperature.\n\n'...
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.'...
                ];
            params.hpt_instruction_practice=[...
                'Now we will test as to when you perceive the warming of the thermode as painful.\n\n'...
                'Your skin will be slowly warmed.\n'...
                'At some point in time you will feel a second sensation on top of the "warm" or "hot" sensation.\n'...
                'The impression of “warmth” or “heat” will change its quality towards \n an additional impression of a “burning”, “stinging”, “drilling” or “aching” sensation.\n'...
                'Please press the ↑ key immediately once you perceive such a change.\n'...
                'Please DO NOT wait to press the stop button until the sensation has become unbearably painful.\n'...
                'Subsequently, the thermode will cool down again, until it reaches the baseline temperature.\n\n'...
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.'...
                ];
            
            params.general_instructions_test=[...
                'We will now start the test round. All procedures are the same than during the practice round.\n\n'... 
                'To start, please indicate whether the device on your skin feels \n cool (←), neutral (↑), or warm (→),.'...
                ];
            params.cdt_instruction_test=[...
                'Just as we have done in the practice round, you will first perceive a cooling of the skin.\n\n'...
                'Please press ↑ key immediately once you perceive \n cooling/decrease of temperature for the first time.\n'...
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.\n'...
                'This procedure will be performed a total of 3 times.'...
                ];
            params.wdt_instruction_test=[...
                'Please press the ↑ key immediately once you perceive \n a warming/increase of temperature for the first time.\n'...
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.\n'...
                'This procedure will be performed a total of 3 times.'...            
                ];
            params.hpt_instruction_test=[...
                'Please press the stop-button immediately as soon as the “warm” or “hot” sensation changes its quality to \n an additional sensation of “burning”, “stinging”, “drilling” or “aching”.\n\n'... 
                'Press the ↑ when you are ready to begin and the procedure will start after afew seconds.\n'...
                'This procedure will be performed a total of 3 times.'...            
                ];
            params.cdt_question='Press when you feel a cooling';
            params.wdt_question='Press when you feel a warming';
            params.hpt_question='Press when you feel a burning, stinging or aching sensation';
    
            params.end_of_task_text='End of task';
            params.inter_trial_text='Wait until next trial';
    end

end